
import { movie } from "./Movie Class.js";

//Array of Movie Objects

export let movieArray = [

    //Coming Soon
    new movie(
        "_TPBE_2022",
        "The Pale Blue Eye",
        "New",
        "A world-weary detective is hired to investigate the murder of a West Point cadet. Stymied by the cadets' code of silence, he enlists one of their own to help unravel the case - a young man the world would come to know as Edgar Allan Poe.",
        true,
        "2h 8m",
        "23-12-2022",
        "/src/images/Coming Soon Movies/TPBE.jfif",
        "https://www.imdb.com/video/vi3371943193/?playlistId=tt14138650?ref_=ext_shr_lnk",
    ),
    new movie(
        "_LY_2022",
        "Lightyear",
        "New",
        "The story of Buzz Lightyear and his adventures to infinity and beyond.",
        true,
        "1h 40m",
        "17-06-2022",
        "/src/images/Coming Soon Movies/Lightyear.jpg",
        "https://www.imdb.com/video/vi1034797593/?playlistId=tt10298810?ref_=ext_shr_lnk",
    ),
    new movie(
        "_N_2022",
        "Nope",
        "New",
        "The residents of a lonely gulch in inland California bear witness to an uncanny and chilling discovery.",
        true,
        "Unknown",
        "22-07-2022",
        "/src/images/Coming Soon Movies/Nope.jpeg",
        "https://www.imdb.com/video/vi3950166809/?playlistId=tt10954984?ref_=ext_shr_lnk",
    ),
    new movie(
        "_FS_2022",
        "Firestarter",
        "New",
        "A young girl tries to understand how she mysteriously gained the power to set things on fire with her mind.",
        true,
        "94 min",
        "13-05-2022",
        "/src/images/Coming Soon Movies/Firestarter.jpg",
        "https://www.imdb.com/video/vi51299097/?playlistId=tt1798632?ref_=ext_shr_lnk",
    ),    new movie(
        "_TBP_2022",
        "The Black Phone",
        "New",
        "After being abducted by a child killer and locked in a soundproof basement, a 13-year-old boy starts receiving calls on a disconnected phone from the killer's previous victims.",
        true,
        "102 min",
        "24-06-2022",
        "/src/images/Coming Soon Movies/The Black phone.jpg",
        "https://www.imdb.com/video/vi3700671001/?playlistId=tt7144666?ref_=ext_shr_lnk"
    ),
    new movie(
        "_M:TRG_2022",
        "Minions: The Rise of Gru",
        "New",
        "The untold story of one twelve-year-old's dream to become the world's greatest supervillain.",
        true,
        "1h 30m",
        "01-07-2022",
        "/src/images/Coming Soon Movies/Minion rise of gru.jpg",
        "https://www.imdb.com/video/vi1941160473/?playlistId=tt5113044?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TG:M_2022",
        "Top Gun: Maverick",
        "New",
        "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
        true,
        "2h 10m",
        "27-07-2022",
        "/src/images/Coming Soon Movies/top_gun.jfif",
        "https://www.imdb.com/video/vi632472089/?playlistId=tt1745960?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TW_2022",
        "The Whale",
        "New",
        "A reclusive, morbidly obese English teacher attempts to reconnect with his estranged teenage daughter.",
        true,
        "1h 57m",
        "09-12-2022",
        "/src/images/Coming Soon Movies/the_whale.jfif",
        "https://www.imdb.com/video/vi2833761561/?playlistId=tt13833688?ref_=ext_shr_lnk",
    ),
    

    //Comedy
    new movie(
        "_TO_2005",
        "The Office",
        "Comedy",
        "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
        false,
        "9 Seasons",
        "2005",
        "/src/images/Movies/The office.jpg",
        "https://www.imdb.com/video/vi2686888217/?playlistId=tt0386676?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TAP_2022",
        "The Adam Project",
        "Comedy",
        "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
        false,
        "1h 46m",
        "11-03-2022",
        "/src/images/Movies/Adam Project.jpg",
        "https://www.imdb.com/video/vi1164886809/?playlistId=tt2463208?ref_=ext_shr_lnk",
    ),
    new movie(
        "_WN_2020",
        "White Noise",
        "Comedy",
        "Dramatizes a contemporary American family's attempts to deal with the mundane conflicts of everyday life while grappling with the universal mysteries of love, death, and the possibility of happiness in an uncertain world.",
        false,
        "2h 16m",
        "01-12-2022",
        "/src/images/Movies/white_noise.jfif",
        "https://www.imdb.com/video/vi4085957913/?playlistId=tt6160448?ref_=ext_shr_lnk",
    ),

    new movie(
        "_FG_2021",
        "Free Guy",
        "Comedy",
        "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
        false,
        "1h 55m",
        "11-08-2021",
        "/src/images/Movies/Free-Guy-poster.png",
        "https://www.imdb.com/video/vi3038887961/?playlistId=tt6264654?ref_=ext_shr_lnk",
    ),

    new movie(
        "_TSS_2021",
        "The Suicide Squad",
        "Comedy",
        "Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        false,
        "2h 12m",
        "05-08-2021",
        "/src/images/Movies/The suicide squad.jpg",
        "https://www.imdb.com/video/vi1024573465/?playlistId=tt6334354?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TWWS_2013",
        "The Wolf of Wall Street",
        "Comedy",
        "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        false,
        "3h",
        "2013",
        "/src/images/Movies/wolf of wall street.jpg",
        "https://www.imdb.com/video/vi2312218649/?playlistId=tt0993846?ref_=ext_shr_lnk"
    ),
    new movie(
        "_EEAO_2022",
        "Everything Everywhere All at Once",
        "Comedy",
        "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
        false,
        "2h 19m",
        "08-04-2022",
        "/src/images/Movies/everything everywhere all at once.jpg",
        "https://www.imdb.com/video/vi1900921625/?playlistId=tt6710474?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TLC_2022",
        "The Lost City",
        "Comedy",
        "A reclusive romance novelist on a book tour with her cover model gets swept up in a kidnapping attempt that lands them both in a cutthroat jungle adventure.",
         false,
         "1h 52m",
         "25-03-2022",
         "/src/images/Movies/the lost city.jpg",
         "https://www.imdb.com/video/vi3826238233/?playlistId=tt13320622?ref_=ext_shr_lnk",
      ),
      new movie(
        "_TSS_2021",
        "The Suicide Squad",
        "Comedy",
        "Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        false,
        "2h 12m",
        "05-08-2021",
        "/src/images/Movies/The suicide squad.jpg",
        "https://www.imdb.com/video/vi1024573465/?playlistId=tt6334354?ref_=ext_shr_lnk",
    ),
    new movie(
        "_FG_2021",
        "Free Guy",
        "Comedy",
        "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
        false,
        "1h 55m",
        "11-08-2021",
        "/src/images/Movies/Free-Guy-poster.png",
        "https://www.imdb.com/video/vi3038887961/?playlistId=tt6264654?ref_=ext_shr_lnk",
    ),

    //Action
    new movie(
        "_TB_2022",
        "The Batman",
        "Action",
        "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        false,
        "2h 56m",
        "04-03-2022",
        "/src/images/Movies/the batman.jpg",
        "https://www.imdb.com/video/vi3215114777/?playlistId=tt1877830?ref_=ext_shr_lnk",
    ),
    new movie(
        "_GOT_2011",
        "Game of Thrones",
        "Action",
        "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
        false,
        "8 Seasons",
        "2011",
        "/src/images/Movies/game of thrones.jpg",
        "https://www.imdb.com/video/vi59490329/?playlistId=tt0944947?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TAP_2022",
        "The Adam Project",
        "Action",
        "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
        false,
        "1h 46m",
        "11-03-2022",
        "/src/images/Movies/Adam Project.jpg",
        "https://www.imdb.com/video/vi1164886809/?playlistId=tt2463208?ref_=ext_shr_lnk",
    ),
    new movie(
      "_TLC_2022",
      "The Lost City",
      "Action",
      "A reclusive romance novelist on a book tour with her cover model gets swept up in a kidnapping attempt that lands them both in a cutthroat jungle adventure.",
       false,
       "1h 52m",
       "25-03-2022",
       "/src/images/Movies/the lost city.jpg",
       "https://www.imdb.com/video/vi3826238233/?playlistId=tt13320622?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TSS_2021",
        "The Suicide Squad",
        "Action",
        "Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
        false,
        "2h 12m",
        "05-08-2021",
        "/src/images/Movies/The suicide squad.jpg",
        "https://www.imdb.com/video/vi1024573465/?playlistId=tt6334354?ref_=ext_shr_lnk",
    ),

    new movie(
        "_BA_2022",
        "Black Adam",
        "Action",
        "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods--and imprisoned just as quickly--Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
        false,
        "2h 5m",
        "21-10-2021",
        "/src/images/Movies/blackadam.jfif",
        "https://www.imdb.com/video/vi3315844377/?playlistId=tt6443346?ref_=ext_shr_lnk",
    ),

    new movie(
        "_V:LTBC_2022",
        "Venom: Let There Be Carnage",
        "Action",
        "Eddie Brock attempts to reignite his career by interviewing serial killer Cletus Kasady, who becomes the host of the symbiote Carnage and escapes prison after a failed execution.",
        false,
        "1h 37m",
        "15-10-2021",
        "/src/images/Movies/venom.jpg",
        "https://www.imdb.com/video/vi1533394969/?playlistId=tt7097896?ref_=ext_shr_lnk",
    ),
    new movie(
        "_E_2022",
        "Emancipation",
        "Action",
        "A runaway slave forges through the swamps of Louisiana on a tortuous journey to escape plantation owners that nearly killed him.",
        false,
        "2h 12m",
        "09-12-2022",
        "/src/images/Movies/emancip.jfif",
        "https://www.imdb.com/video/vi2281686297/?playlistId=tt12530246?ref_=ext_shr_lnk",
    ),

    new movie(
        "_EEAO_2022",
        "Everything Everywhere All at Once",
        "Action",
        "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
        false,
        "2h 19m",
        "08-04-2022",
        "/src/images/Movies/everything everywhere all at once.jpg",
        "https://www.imdb.com/video/vi1900921625/?playlistId=tt6710474?ref_=ext_shr_lnk",
    ),
    new movie(
        "_RE:WRC_2021",
        "Resident Evil: Welcome to Raccoon City",
        "Action",
        "Set in 1998, this origin story explores the secrets of the mysterious Spencer Mansion and the ill-fated Raccoon City.",
        false,
        "1h 47m",
        "24-11-2021",
        "/src/images/Movies/reident evil.jpg",
        "https://www.imdb.com/video/vi1022935833/?playlistId=tt6920084?ref_=ext_shr_lnk",
    ),

    //Horror
    new movie(
      "_Z_2009",
      "Zombieland",
      "Horror",
      "A shy student trying to reach his family in Ohio, a gun-toting bruiser in search of the last Twinkie and a pair of sisters striving to get to an amusement park join forces in a trek across a zombie-filled America.",
      false,
      "1h 28m",
      "25-09-2009",
      "/src/images/Movies/zombieland.png",
      "https://www.imdb.com/video/vi179635481/?playlistId=tt1156398?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TNH_2020",
        "The Night House",
        "Horror",
        "A widow begins to uncover her recently deceased husband's disturbing secrets.",
        false,
        "1h 47m",
        "20-08-2020",
        "/src/images/Movies/the night house.jpg",
        "https://www.imdb.com/video/vi981188633/?playlistId=tt9731534?ref_=ext_shr_lnk",
    ),
    new movie(
        "_TFP_2021",
        "The Forever Purge",
        "Horror",
        "All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end.",
        false,
        "1h 43m",
        "08-07-2021",
        "/src/images/Movies/the forever purge.jpg",
        "https://www.imdb.com/video/vi3873423385/?playlistId=tt10327252?ref_=ext_shr_lnk",
    ),
    new movie(
        "_H_2013",
        "Hannibal",
        "Horror",
        "Explores the early relationship between renowned psychiatrist Hannibal Lecter and a young FBI criminal profiler who is haunted by his ability to empathize with serial killers.",
        false,
        "3 Seasons",
        "2013",
        "/src/images/Movies/Hannibal.jpg",
        "https://www.imdb.com/video/vi2278993945/?playlistId=tt2243973?ref_=ext_shr_lnk",
    ),
    new movie(
        "_RE:WRC_2021",
        "Resident Evil: Welcome to Raccoon City",
        "Horror",
        "Set in 1998, this origin story explores the secrets of the mysterious Spencer Mansion and the ill-fated Raccoon City.",
        false,
        "1h 47m",
        "24-11-2021",
        "/src/images/Movies/reident evil.jpg",
        "https://www.imdb.com/video/vi1022935833/?playlistId=tt6920084?ref_=ext_shr_lnk",
    ),
    new movie(
        "_AQP_2018",
        "A Quiet Place",
        "Horror",
        "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
        false,
        "1h 30m",
        "06-04-2018",
        "/src/images/Movies/quiet place.jpg",
        "https://www.imdb.com/video/vi3446716441/?playlistId=tt6644200?ref_=ext_shr_lnk",
    ),
    new movie(
        "_ST_",
        "Stranger Things",
        "Horror",
        "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
        false,
        "2 Seasons",
        "2016",
        "/src/images/Movies/Stranger things.jpg",
        "https://www.imdb.com/video/vi1386398233/?playlistId=tt4574334?ref_=ext_shr_lnk",
    ),
    
    new movie(
        "_TWD_",
        "The Walking Dead",
        "Horror",
        "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
        false,
        "11 Seasons",
        "2010",
        "/src/images/Movies/The walking dead.jpg",
        "https://www.imdb.com/video/vi1612366617/?playlistId=tt1520211?ref_=ext_shr_lnk"
    ),

    //Anime/Animation
    new movie(
        "_TR_2022",
        "Turning Red",
        "Animation",
        "A 13-year-old girl named Meilin turns into a giant red panda whenever she gets too excited",
        false,
        "1h 40m",
        "11-03-2022",
        "/src/images/Movies/turning red.webp",
        "https://www.imdb.com/video/vi3974546201/?playlistId=tt8097030?ref_=ext_shr_lnk",
    ),
    new movie(
        "_DS_2019",
        "Demon Slayer: Kimetsu no Yaiba",
        "Animation",
        "A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.",
        false,
        "2019 - ",
        "2019",
        "/src/images/Movies/Demon slayer.jpg",
        "https://www.imdb.com/video/vi2476588825/?playlistId=tt9335498?ref_=ext_shr_lnk",
    ),
    new movie(
        "_N_2002",
        "Naruto",
        "Animation",
        "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
        false,
        "5 Seasons",
        "2002",
        "/src/images/Movies/naruto.jpg",
        "https://www.imdb.com/video/vi3113746713/?playlistId=tt0409591?ref_=ext_shr_lnk",
    ),
    new movie(
       "_S_2016",
       "Sing",
       "Animation",
       "In a city of humanoid animals, a hustling theater impresario's attempt to save his theater with a singing competition becomes grander than he anticipates even as its finalists find that their lives will never be the same.",
       false,
       "1h 48m",
       "2016",
       "/src/images/Movies/sing.jpg",
       "https://www.imdb.com/video/vi1172485657/?playlistId=tt3470600?ref_=ext_shr_lnk"
    ),
    new movie(
        "_S_2001",
        "Shrek",
        "Animation",
        "Shrek, an ogre, embarks on a journey with a donkey to rescue Princess Fiona from a vile lord and regain his swamp.",
        false,
        "1h 30m",
        "2001",
        "/src/images/Movies/shrek.jpg",
        "https://www.imdb.com/video/vi4085711129/?playlistId=tt0126029?ref_=ext_shr_lnk",
    ),
    new movie(
        "_E_2022",
        "Encanto",
        "Animation",
        "A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.",
        false,
        "1h 42m",
        "2022",
        "/src/images/Movies/encanto.jpeg",
        "https://www.imdb.com/video/vi4093755417/?playlistId=tt2953050?ref_=ext_shr_lnk"
    ),
    new movie(
        "_JK_2020",
        "Jujutsu Kaisen",
        "Animation",
        "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
        false,
        "2020 - ",
        "2020",
        "/src/images/Movies/jujutsu kaisen.jpg",
        "https://www.imdb.com/video/vi1065664793/?playlistId=tt12343534?ref_=ext_shr_lnk"
    ),
    new movie(
        "_TIAABW_2022",
        "The Ice Age Adventures of Buck Wild",
        "Animation",
        "The Ice Age Adventures of Buck Wild continues the escapades of the possum brothers Crash and Eddie who set out to find a place of their own. Together with the one-eyed weasel, Buck Wild, they face the dinosaurs who inhabit the Lost World.",
        false,
        "1h 22m",
        "28-01-2022",
        "/src/images/Movies/buck ice age.jpg",
        "https://www.imdb.com/video/vi1010418457/?playlistId=tt13634480?ref_=ext_shr_lnk"
    ),
]